name: bacaku
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/launc.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/images/
    - assets/flashcard/
    - assets/audio/
    - assets/kosa/
    - assets/cerita/
    - assets/cerita/audio_cerita/
    - assets/cerita/zian_dan_micho/
    - assets/cerita/hewan_di_laut/
    - assets/cerita/aku_dan_kucingku/
    - assets/cerita/saat_libur_sekolah/
    - assets/cerita/uli_kupu_kupu_yang_indah/
    - assets/cerita/izan_suka_olahraga/
    - assets/cerita/indah_anak_yang_mandiri/
    - assets/cerita/5_sekawan/
    - assets/cerita/apel_yang_manis/
    - assets/cerita/aku_senang_sekolah/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
